export interface DeliveryZone {
  name: string;
  feeKz: number;
}

const RAW_ZONES: DeliveryZone[] = [
  { name: "Coreia", feeKz: 500 },
  { name: "Zamba 2", feeKz: 1000 },
  { name: "Chicala", feeKz: 1500 },
  { name: "Bairro Azul", feeKz: 1500 },
  { name: "Praia do Bispo", feeKz: 1500 },
  { name: "Mutamba", feeKz: 1500 },
  { name: "Coqueiros", feeKz: 1500 },
  { name: "Nova Marginal", feeKz: 1500 },
  { name: "Palácio da Justiça", feeKz: 1500 },
  { name: "Cidade Alta", feeKz: 1500 },
  { name: "Antiga Marginal", feeKz: 2000 },
  { name: "Ilha", feeKz: 2000 },
  { name: "Kinaxixi", feeKz: 2000 },
  { name: "Maculusso", feeKz: 2000 },
  { name: "Maianga", feeKz: 2000 },
  { name: "Rainha Ginga", feeKz: 2000 },
  { name: "Cassenda", feeKz: 2000 },
  { name: "Prenda", feeKz: 2000 },
  { name: "Márteris", feeKz: 2000 },
  { name: "1º de Maio", feeKz: 2000 },
  { name: "Cruzeiro", feeKz: 2000 },
  { name: "Serpa Pinto", feeKz: 2000 },
  { name: "Porto de Luanda", feeKz: 2000 },
  { name: "Alvalade", feeKz: 2000 },
  { name: "Ingombotas", feeKz: 2000 },
  { name: "Avenida Brasil", feeKz: 2500 },
  { name: "São Paulo", feeKz: 2500 },
  { name: "Miramar", feeKz: 2500 },
  { name: "Bairro Operário", feeKz: 2500 },
  { name: "Combatentes", feeKz: 2500 },
  { name: "Zé Pirão", feeKz: 2500 },
  { name: "Vila Alice", feeKz: 2500 },
  { name: "Samba", feeKz: 2500 },
  { name: "Cassequel", feeKz: 2500 },
  { name: "Aeroporto", feeKz: 2500 },
  { name: "Anangola", feeKz: 2500 },
  { name: "Morro Bento", feeKz: 3500 },
  { name: "Corimba", feeKz: 3500 },
  { name: "Boa Vista", feeKz: 3500 },
  { name: "Bairro Popular", feeKz: 3500 },
  { name: "Palanca", feeKz: 3500 },
  { name: "MultiPerfil", feeKz: 3500 },
  { name: "Congoleses", feeKz: 3500 },
  { name: "Filda", feeKz: 3500 },
  { name: "Rangel", feeKz: 3500 },
  { name: "Gamek à Direita", feeKz: 3500 },
  { name: "Cazenga", feeKz: 3500 },
  { name: "Cuca", feeKz: 3500 },
  { name: "Sambizanga", feeKz: 3500 },
  { name: "Brigada", feeKz: 3500 },
  { name: "Sanatório", feeKz: 4000 },
  { name: "Vila da Gamek", feeKz: 4000 },
  { name: "Dangereux", feeKz: 6000 },
  { name: "Fubú", feeKz: 5500 },
  { name: "Nova Vida", feeKz: 5000 },
  { name: "Talatona", feeKz: 5000 },
  { name: "Futungo", feeKz: 5000 },
  { name: "Calemba 2", feeKz: 5000 },
  { name: "Antes da Vila de Viana", feeKz: 5000 },
  { name: "Golf II", feeKz: 6000 },
  { name: "Patriota", feeKz: 6500 },
  { name: "Benfica", feeKz: 7000 },
  { name: "Via Expressa", feeKz: 7000 },
  { name: "Vila Viana", feeKz: 7000 },
  { name: "Cacuaco", feeKz: 7000 },
  { name: "Camama", feeKz: 7000 },
  { name: "Luanda Sul", feeKz: 7000 },
  { name: "Kilamba", feeKz: 8000 },
  { name: "Vida Pacífica", feeKz: 9000 },
  { name: "Zango 0", feeKz: 9000 },
  { name: "Zango 3", feeKz: 10000 },
];

export const DELIVERY_ZONES: DeliveryZone[] = [...RAW_ZONES].sort((a, b) =>
  a.name.localeCompare(b.name, "pt")
);

export function findDeliveryZone(name: string): DeliveryZone | undefined {
  return DELIVERY_ZONES.find((z) => z.name === name);
}
